#!/usr/bin/env bash

function print_help() {
  cat <<EOF
Take a command to run and show an animation while the command is runing.

  Usage: progress [OPTIONS] [FLAGS]

  Example:
    progress bar 4 -c sleep 4 && echo done


 OPTIONS:
  help: Print this message and exit.


  FLAGS:
    -t --type: Type of animation, options: progress_bar, spinner.
    -d, --duration: The duration of the animation, any number greater then 1, in seconds.
    -c: Command to run.
    -h, --help: Print this message and exit.



 Made by theacebutler, Aug 2026


EOF
}

__type=
__duration=0
# Symbols
__spinner_symbols=(
  "-"
  "\\"
  "|"
  "-"
  "|"
  "/"
)
function spinner() {
  while true; do
    for s in "${__spinner_symbols[@]}"; do
      sleep 0.2
      printf "\r%s" "$s"
    done
  done
}

function print_bar() {
  # print a progress symvbole * $1 amount of time, $1 is what is left out to fill
  for _ in $(seq 0 "$1"); do
    printf "|"
  done
}

function print_space() {
  # print a " " * $1 amount of time, $1 is what is left out to fill
  for _ in $(seq 0 "$1"); do
    printf " "
  done
}

function progress_bar() {
  local duration step pos
  duration="$1"
  step=$((100 / duration))
  for pos in $(seq 0 $((duration))); do
    printf "\r"
    printf "[ %s%s ]" "$((pos * step))" "%"
    printf "["
    print_bar $((step * pos))
    print_space $((step * $((duration - pos))))
    printf "]"
    if ((pos < duration)); then
      sleep 1
    fi
  done
  printf "\r\n"
}

function main() {
  while [ $# -gt 0 ]; do
    case "$1" in
    "bar")
      __type="bar"
      ;;
    "spinner")
      __type="spinner"
      ;;
    "-d" | "--duration")
      __duration="$2"
      shift
      ;;
    "help")
      print_help
      exit 0
      ;;
    *)
      print_help
      exit 1
      ;;
    esac
    shift
  case "$__type" in
  "spinner")
    unset "$__pid"
    spinner &
    __pid="$!"
  "bar")
    unset "$__pid"
    progress_bar "$__duration" &
    __pid="$!"
    printf "\r"
    ;;
  "bar")
    unset "$__pid"
    progress_bar "$__duration" &
    __pid="$!"
    trap 'kill $__pid 2>/dev/null; echo ' "SIGINT"
    # run the users command
    $__command &&
      kill $__pid 2>/dev/null
    printf "\r"
    ;;
  esac
}
main "$@"
