#!/usr/bin/env bash

function print_help() {
  cat <<EOF
Take a command to run and show an animation while the command is runing.

  Usage: progress [OPTIONS] [FLAGS]

  Example:
    progress bar 4 -c sleep 4 


 OPTIONS:
  help: Print this message and exit.
  bar: Show a progress bar, takes a duration in seconds. Best for commands where time is known.
  spinner: Show a spinner, does not take a duration, best for commands where time is unknown.


  FLAGS:
    -d, --duration: The duration of the animation, any number greater then 1, in seconds.
    -c: Command to run.
    -h, --help: Print this message and exit.



 Made by theacebutler, Aug 2026


EOF
}

__type=
__duration=
__command=
# Symbols
__spinner_symbols=(
  "-"
  "\\"
  "|"
  "-"
  "|"
  "/"
)
function spinner() {
  while true; do
    for s in "${__spinner_symbols[@]}"; do
      sleep 0.2
      printf "\r%s" "$s"
    done
  done
}

function print_bar() {
  # print a progress symvbole * $1 amount of time, $1 is what is left out to fill
  for _ in $(seq 0 "$1"); do
    printf "|"
  done
}

function print_space() {
  # print a " " * $1 amount of time, $1 is what is left out to fill
  for _ in $(seq 0 "$1"); do
    printf " "
  done
}

function progress_bar() {
  local duration step pos
  duration="$1"
  step=$((100 / duration))
  for pos in $(seq 0 $((duration))); do
    printf "\r"
    printf "[ %s%s ]" "$((pos * step))" "%"
    printf "["
    print_bar $((step * pos))
    print_space $((step * $((duration - pos))))
    printf "]"
    if ((pos < duration)); then
      sleep 1
    fi
  done
  printf "\r\n"
}

function main() {
  # take in user flags for type duration(for the 'bar' option) and command to run
  while [ $# -gt 0 ]; do
    case "$1" in
    "bar")
      __type="bar"
      ;;
    "spinner")
      __type="spinner"
      ;;
    "-d" | "--duration")
      __duration="$2"
      shift
      ;;
    "-c" | "--command")
      shift
      __command=$*
      break
      ;;
    "help")
      print_help
      exit 0
      ;;
    *)
      print_help
      exit 1
      ;;
    esac
    shift
  done

  if [[ -z "$__command" ]]; then
    print_help
    exit 1
  fi
  case "$__type" in
  "spinner")
    unset "$__pid"
    if [[ -z "$__command" ]]; then
      exit 1
    fi
    spinner &
    __pid="$!"
    trap 'kill $__pid 2>/dev/null' "SIGINT"
    $__command &&
      kill $__pid 2>/dev/null
    printf "\r"
    ;;
  "bar")
    if [[ -z "$__duration" ]]; then
      print_help
      exit 1
    fi
    unset "$__pid"
    progress_bar "$__duration" &
    __pid="$!"
    trap 'kill $__pid 2>/dev/null' "SIGINT"
    # run the users command
    $__command &&
      kill $__pid 2>/dev/null
    printf "\r"
    ;;
  esac
  printf "\n"
}

main "$@"
